site_name: "Yummy Stuff"
site_url: "https://yummy.duchardt.net"
theme:
  name: readthedocs
plugins:
  - exclude:
      glob:
        - Food/*Journal.md
  - search:
      lang: en
      prebuild_index: true
