site_name: Yummy Stuff
site_url: "https://yummy.duchardt.net/"

theme:
  name: readthedocs
docs_dir: docs

copyright: ""
dev_addr: 0.0.0.0:8000
use_directory_urls: false

strict: true
plugins:
  - exclude:
      glob:
        - Food/*Journal.md
  - search:
      lang: en
      prebuild_index: true
