apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mkdocs.fullname" . }}
  labels:
    {{ include "mkdocs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "mkdocs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "mkdocs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mkdocs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command:
            {{ toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{ toYaml .Values.args | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            {{ toYaml .Values.env | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /docs
              name: docs
      {{- with .Values.nodeSelector }}
      volumes:
        - name: docs
          hostPath:
            path: /volumes/syncthing/BubaFritzShare/private
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
