# Default values for mkdocs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/fritzduchardt/mkdocs
  pullPolicy: Always
  tag: "main"

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

service:
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  host: yummy.duchardt.net

env: []

command: ["mkdocs", "serve"]
args: ["--dev-addr", "0.0.0.0:8000"]

nodeSelector:
  kubernetes.io/hostname: friclu-1

hostPath: /volumes/syncthing/BubaFritzShare/private

mkdocsConfig:
  site_name: Yummy Stuff
  site_url: "https://yummy.duchardt.net/"

  theme:
    name: readthedocs
  docs_dir: docs

  copyright: ""
  use_directory_urls: false

  strict: true
  plugins:
    - exclude:
        glob:
          - Food/*Journal.md
    - search:
        lang: en
        prebuild_index: true
