# Default values for mkdocs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/fritzduchardt/mkdocs
  pullPolicy: Always
  tag: "main"

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

service:
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  host: yummy.duchardt.net

env: []

command: ["mkdocs", "serve"]
args: ["server", "--dev-addr", ""]

nodeSelector:
  kubernetes.io/hostname: friclu-1
